### ISSUE TITLE
Making a new app whose name has a space in it fails

### ISSUE THREAD

**Issue by icevans** [unnamed-paas/paas#19]
This raises an "inavlid reference" error from Docker. The issue is that when we set the network name, we don't slugify it, but network names can't have spaces.

**Comment by jkulton** [comment]
This and #15 are similar to one another.

I noticed on Heroku they require project names to be made up of only lowercase letters, numbers, and dashes. That might be a good change for us. Obviously we’ll still validate all this, but it means the application title is closer to the formatting we need it for in the service, network, etc.

**Comment by jkulton** [comment]
This and #15 are similar to one another.

It may benefit us to just enforce a stricter naming convention up front. Maybe lowercase letters, numbers, and dashes (or underscores?). We can validate this on the API endpoint (and return a message if formatting is off) and then the stored value won't require so much transformation and handling when we're working with Docker.

**Comment by jkulton** [comment]
Addressed in #33
