### ISSUE TITLE
set up dockerignore files so we don't build unnecessary stuff into our images

### ISSUE THREAD

**Issue by icevans** [unnamed-paas/paas#2]

**Comment by bharatagarwal** [comment]
@icevans when your deploy got tripped up by the `.git` folder, was it in the process of inflating the zip file?

If we're directly porting over the zip file given by the user, that's something we don't have control over -- whether the zip has `node_modules` or `.git` or `.env` folder from before.

One way could be to inflate the zip file in the `uploads` directory, remove the files we don't want to carry over, and then zip again and send to the manager node.

Also, I'm curious about what `tar.pack` does, maybe we don't even need to zip the file back at all.

**Comment by bharatagarwal** [comment]
Steps to take:

- Unzip the file into the version subdirectory
- detect rack / node from subdirectory
- populate dockerfile accordingly
- create a dockerignore file
- check for presence of sql files for schema
- enter subdirectory into Dockerfile
- tear down the content of the subdirectory, leaving the zip in place for future rollbacks
