### ISSUE TITLE
Generate UUID to append to docker-machine name

### ISSUE THREAD

**Issue by bharatagarwal** [unnamed-paas/paas#3]
Can do with SecureRandom from ruby stdlib

```ruby
require 'securerandom'

SecureRandom.uuid # => "67909d17-4867-44b2-a43c-c1607584abb1"
```

Ian: The UUID should also be attached to the zip filename

**Comment by jkulton** [comment]
Since we’re now swapping to Node this appears to be the most popular option: [node-uuid](https://github.com/kelektiv/node-uuid)
