### ISSUE TITLE
Explore using xterm for build stream and providing terminal for container

### ISSUE THREAD

**Issue by bharatagarwal** [unnamed-paas/paas#42]
https://xtermjs.org
https://dev.to/davidk01/ptyjs--xtermjs--shell-in-your-browser-1f9c
https://stackoverflow.com/questions/45924485/how-to-create-web-based-terminal-using-xterm-js-to-ssh-into-a-system-on-local-ne

**Comment by bharatagarwal** [comment]
@ice We can close this one, right?

**Comment by icevans** [comment]
@bharatagarwal  Yep
