### ISSUE TITLE
Use Docker API instead of executing shell commands

### ISSUE THREAD

**Issue by icevans** [unnamed-paas/paas#6]
Now that we know how to connect the API to a remote machine: https://3.basecamp.com/3695031/buckets/14090263/messages/2195554342

**Comment by icevans** [comment]
Use this library now that we've switched to Node: https://github.com/apocas/dockerode

And possibly this one to interface with Docker Machine: https://github.com/mikejmoore/docker-swarm-sdk

**Comment by jkulton** [comment]
Handled in #11 , #12 , and [fa3edf0](https://github.com/unnamed-paas/paas/commit/fa3edf0736f9dfabfc3f45743be25ea12819cfb1)
